-- 投入先のDBを指定;
CONNECT TO SAMPLE2;
-- 一般ユーザのスキーマを指定;
SET SCHEMA sample;
CREATE TABLE CODE_NAME (
  CODE_ID CHARACTER(8) NOT NULL,
  CODE_VALUE VARCHAR(2) NOT NULL,
  LANG CHARACTER(2) NOT NULL,
  SORT_ORDER SMALLINT NOT NULL,
  CODE_NAME VARCHAR(50) NOT NULL,
  SHORT_NAME VARCHAR(50),
  OPTION01 VARCHAR(50),
  OPTION02 VARCHAR(50),
  OPTION03 VARCHAR(50),
  OPTION04 VARCHAR(50),
  OPTION05 VARCHAR(50),
  OPTION06 VARCHAR(50),
  OPTION07 VARCHAR(50),
  OPTION08 VARCHAR(50),
  OPTION09 VARCHAR(50),
  OPTION10 VARCHAR(50)
);
CREATE TABLE CODE_PATTERN (
  CODE_ID CHARACTER(8) NOT NULL,
  CODE_VALUE VARCHAR(2) NOT NULL,
  PATTERN01 CHARACTER(1) NOT NULL,
  PATTERN02 CHARACTER(1),
  PATTERN03 CHARACTER(1),
  PATTERN04 CHARACTER(1),
  PATTERN05 CHARACTER(1),
  PATTERN06 CHARACTER(1),
  PATTERN07 CHARACTER(1),
  PATTERN08 CHARACTER(1),
  PATTERN09 CHARACTER(1),
  PATTERN10 CHARACTER(1),
  PATTERN11 CHARACTER(1),
  PATTERN12 CHARACTER(1),
  PATTERN13 CHARACTER(1),
  PATTERN14 CHARACTER(1),
  PATTERN15 CHARACTER(1),
  PATTERN16 CHARACTER(1),
  PATTERN17 CHARACTER(1),
  PATTERN18 CHARACTER(1),
  PATTERN19 CHARACTER(1),
  PATTERN20 CHARACTER(1)
);
CREATE TABLE USER_SESSION (
  SESSION_ID VARCHAR(100) NOT NULL,
  SESSION_OBJECT BLOB(2147483647) NOT NULL,
  EXPIRATION_DATETIME TIMESTAMP NOT NULL
);
ALTER TABLE USER_SESSION ADD CONSTRAINT PK_USER_SESSION PRIMARY KEY
(
  SESSION_ID
);
ALTER TABLE CODE_PATTERN ADD CONSTRAINT SYS_C0058550 PRIMARY KEY
(
  CODE_ID,
  CODE_VALUE
);
ALTER TABLE CODE_NAME ADD CONSTRAINT SYS_C0058560 PRIMARY KEY
(
  CODE_ID,
  CODE_VALUE,
  LANG
);
ALTER TABLE CODE_NAME ADD FOREIGN KEY (
  CODE_ID,
  CODE_VALUE
) REFERENCES CODE_PATTERN (
  CODE_ID,
  CODE_VALUE
);
